[versions]
# Build tools
agp = "8.10.1"

kotlin = "2.1.0"

# Android SDK
minSdk = "23"
compileSdk = "36"
targetSdk="36"

# Core libs
coroutines = "1.9.0"

# AndroidX (kept for future use)
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
compose = "1.6.8"
composeCompiler = "1.5.14"
kotlinxBinaryValidator = "0.14.0"

# Testing
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
material3Android = "1.4.0"

compose-bom = "2024.10.00"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
nexusPublish = "2.0.0"

[plugins]
gradle-nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublish" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library     = { id = "com.android.library",     version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-binary-compatibility = {id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinxBinaryValidator" }

# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }


[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-runtime-collect = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose" }

kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }


activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }

compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }



compose-material3 = { group = "androidx.compose.material3", name = "material3" }

compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }